# Generated by Agentic AI System for Nova_8
# Detected language: JavaScript
# Detected frameworks: react

FROM node:18-alpine

# Install serve for production static file serving
RUN npm install -g serve

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build application
RUN npm run build

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -qO- http://localhost:3000 || exit 1

# Start application
CMD ["npx", "serve", "-s", "build"]
